var dungeonLocation = [
	"A building in a city",
	"Catacombs or sewers beneath a city",
	"Beneath a farmhouse",
	"Beneath a graveyard",
	"Beneath a ruined castle",
	"Beneath a ruined city",
	"Beneath a temple",
	"In a chasm",
	"In a cliff face",
	"In a desert",
	"In a forest",
	"In a glacier",
	"In a gorge",
	"In a jungle",
	"In a mountain pass",
	"In a swamp",
	"Beneath or on top of a mesa",
	"In sea caves",
	"In several conn ected mesas",
	"On a mountain peak",
	"On a promontory",
	"On an island",
	"Underwater",
	"Roll on the Exotic Location table"
];